import { CompanyConfigurations } from '@interfaces/IUtilsCompanyList';

export const LINK = 'https://boards-api.greenhouse.io/v1/boards';

export const companyConfig: CompanyConfigurations = {
  greenhouse: {
    rvohealth: {
      title: 'RVO Health',
      name: 'rvohealth',
      backendApi: `${LINK}/rvohealth/jobs`,
      active: true,
    },
    redventures: {
      title: 'Red Ventures',
      name: 'redventures',
      backendApi: `${LINK}/redventures/jobs`,
      active: true,
    },
    airbnb: {
      title: 'Airbnb',
      name: 'airbnb',
      backendApi: `${LINK}/airbnb/jobs`,
      active: true,
    },
    dropbox: {
      title: 'Dropbox',
      name: 'dropbox',
      backendApi: `${LINK}/dropbox/jobs`,
      active: true,
    },
    instacart: {
      title: 'Instacart',
      name: 'instacart',
      backendApi: `${LINK}/instacart/jobs`,
      active: true,
    },
    stripe: {
      title: 'Stripe',
      name: 'stripe',
      backendApi: `${LINK}/stripe/jobs`,
      active: true,
    },
    greenhouse: {
      title: 'Greenhouse',
      name: 'greenhouse',
      backendApi: `${LINK}/greenhouse/jobs`,
      active: true,
    },
    reddit: {
      title: 'Reddit',
      name: 'reddit',
      backendApi: `${LINK}/reddit/jobs`,
      active: true,
    },
    robinhood: {
      title: 'Robinhood',
      name: 'robinhood',
      backendApi: `${LINK}/robinhood/jobs`,
      active: true,
    },
    twitch: {
      title: 'Twitch',
      name: 'twitch',
      backendApi: `${LINK}/twitch/jobs`,
      active: true,
    },
    godaddy: {
      title: 'GoDaddy',
      name: 'godaddy',
      backendApi: `${LINK}/godaddy/jobs`,
      active: true,
    },
    nerdwallet: {
      title: 'NerdWallet',
      name: 'nerdwallet',
      backendApi: `${LINK}/nerdwallet/jobs`,
      active: true,
    },
    pinterest: {
      title: 'Pinterest',
      name: 'pinterest',
      backendApi: `${LINK}/pinterest/jobs`,
      active: true,
    },
    wayfair: {
      title: 'Wayfair',
      name: 'wayfair',
      backendApi: `${LINK}/wayfair/jobs`,
      active: true,
    },
    learfield: {
      title: 'Learfield',
      name: 'learfield',
      backendApi: `${LINK}/learfield/jobs`,
      active: true,
    },
    monumentalsports: {
      title: 'Monumental Sports',
      name: 'monumentalsports',
      backendApi: `${LINK}/monumentalsports/jobs`,
      active: true,
    },
    redcanary: {
      title: 'Red Canary',
      name: 'redcanary',
      backendApi: `${LINK}/redcanary/jobs`,
      active: false,
    },
    threeflow: {
      title: 'Three Flow',
      name: 'threeflow',
      backendApi: `${LINK}/threeflow/jobs`,
      active: true,
    },
    gitlab: {
      title: 'GitLab',
      name: 'gitlab',
      backendApi: `${LINK}/gitlab/jobs`,
      active: true,
    },
    figma: {
      title: 'Figma',
      name: 'figma',
      backendApi: `${LINK}/figma/jobs`,
      active: true,
    },
    voltrondata: {
      title: 'Voltron Data',
      name: 'voltrondata',
      backendApi: `${LINK}/voltrondata/jobs`,
      active: true,
    },
    doximity: {
      title: 'Doximity',
      name: 'doximity',
      backendApi: `${LINK}/doximity/jobs`,
      active: true,
    },
    agentsync: {
      title: 'Agent Sync',
      name: 'agentsync',
      backendApi: `${LINK}/agentsync/jobs`,
      active: true,
    },
    protagonist: {
      title: 'Protagonist',
      name: 'protagonist',
      backendApi: `${LINK}/protagonist/jobs`,
      active: true,
    },
    fearless: {
      title: 'Fearless',
      name: 'fearless',
      backendApi: `${LINK}/fearless/jobs`,
      active: true,
    },
    parachutehealth: {
      title: 'Parachute Health',
      name: 'parachutehealth',
      backendApi: `${LINK}/parachutehealth/jobs`,
      active: true,
    },
    lyft: {
      title: 'Lyft',
      name: 'lyft',
      backendApi: `${LINK}/lyft/jobs`,
      active: true,
    },
    okta: {
      title: 'Okta',
      name: 'okta',
      backendApi: `${LINK}/okta/jobs`,
      active: true,
    },
    warbyparker: {
      title: 'Warby Parker',
      name: 'warbyparker',
      backendApi: `${LINK}/warbyparker/jobs`,
      active: true,
    },
    calm: {
      title: 'Calm',
      name: 'calm',
      backendApi: `${LINK}/calm/jobs`,
      active: true,
    },
    cruise: {
      title: 'Cruise',
      name: 'cruise',
      backendApi: `${LINK}/cruise/jobs`,
      active: true,
    },
    doordash: {
      title: 'DoorDash',
      name: 'doordash',
      backendApi: `${LINK}/doordashusa/jobs`,
      active: true,
    },
    gusto: {
      title: 'Gusto',
      name: 'gusto',
      backendApi: `${LINK}/gusto/jobs`,
      active: true,
    },
    lattice: {
      title: 'Lattice',
      name: 'lattice',
      backendApi: `${LINK}/lattice/jobs`,
      active: true,
    },
    fabric: {
      title: 'Fabric',
      name: 'fabric',
      backendApi: `${LINK}/fabric83/jobs`,
      active: true,
    },
    cerebral: {
      title: 'Cerebral',
      name: 'cerebral',
      backendApi: `${LINK}/cerebral/jobs`,
      active: true,
    },
    snyk: {
      title: 'Snyk',
      name: 'snyk',
      backendApi: `${LINK}/snyk/jobs`,
      active: true,
    },
    strava: {
      title: 'Strava',
      name: 'strava',
      backendApi: `${LINK}/strava/jobs`,
      active: true,
    },
    calendly: {
      title: 'Calendly',
      name: 'calendly',
      backendApi: `${LINK}/calendly/jobs`,
      active: true,
    },
    linkedin: {
      title: 'LinkedIn',
      name: 'linkedin',
      backendApi: `${LINK}/linkedin/jobs`,
      active: true,
    },
    smartsheet: {
      title: 'Smartsheet',
      name: 'smartsheet',
      backendApi: `${LINK}/smartsheet/jobs`,
      active: true,
    },
    exodus54: {
      title: 'Exodus54',
      name: 'exodus54',
      backendApi: `${LINK}/exodus54/jobs`,
      active: true,
    },
    zwift: {
      title: 'Zwift',
      name: 'zwift',
      backendApi: `${LINK}/zwift/jobs`,
      active: true,
    },
    euclidpower: {
      title: 'Euclid Power',
      name: 'euclidpower',
      backendApi: `${LINK}/euclidpower/jobs`,
      active: true,
    },
  },
  workday: {
    bah: {
      title: 'Booz Allen Hamilton',
      name: 'bah',
      basePathObject: {
        basePath: 'bah/BAH_Jobs/jobs',
        wdNum: 'wd1',
      },
      frontendUrl: 'https://bah.wd1.myworkdayjobs.com/BAH_Jobs',
      active: true,
    },
    caci: {
      title: 'CACI International',
      name: 'caci',
      basePathObject: {
        basePath: 'caci/External/jobs',
        wdNum: 'wd1',
      },
      frontendUrl: 'https://caci.wd1.myworkdayjobs.com/External',
      active: true,
    },
    accenture: {
      title: 'Accenture',
      name: 'accenture',
      basePathObject: {
        basePath: 'accenture/AccentureCareers/jobs',
        wdNum: 'wd103',
      },
      frontendUrl: 'https://accenture.wd103.myworkdayjobs.com/AccentureCareers',
      active: true,
    },
    nvidia: {
      title: 'NVIDIA',
      name: 'nvidia',
      basePathObject: {
        basePath: 'nvidia/NVIDIAExternalCareerSite/jobs',
        wdNum: 'wd5',
      },
      frontendUrl:
        'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite',
      active: true,
    },
    patagonia: {
      title: 'Patagonia',
      name: 'patagonia',
      basePathObject: {
        basePath: 'patagonia/PWCareers/jobs',
        wdNum: 'wd5',
      },
      frontendUrl: 'https://patagonia.wd5.myworkdayjobs.com/PWCareers',
      active: true,
    },
    georgetown: {
      title: 'Georgetown University',
      name: 'georgetown',
      basePathObject: {
        basePath: 'georgetown/Georgetown_Admin_Careers/jobs',
        wdNum: 'wd1',
      },
      frontendUrl:
        'https://georgetown.wd1.myworkdayjobs.com/Georgetown_Admin_Careers',
      active: true,
    },
    travelers: {
      title: 'Travelers',
      name: 'travelers',
      basePathObject: {
        basePath: 'travelers/External/jobs',
        wdNum: 'wd5',
      },
      frontendUrl: 'https://travelers.wd5.myworkdayjobs.com/External',
      active: true,
    },
    thehartford: {
      title: 'The Hartford',
      name: 'thehartford',
      basePathObject: {
        basePath: 'thehartford/Careers_External/jobs',
        wdNum: 'wd5',
      },
      frontendUrl: 'https://thehartford.wd5.myworkdayjobs.com/Careers_External',
      active: true,
    },
    capitalone: {
      title: 'Capital One',
      name: 'capitalone',
      basePathObject: {
        basePath: 'capitalone/Capital_One/jobs',
        wdNum: 'wd12',
      },
      frontendUrl: 'https://capitalone.wd12.myworkdayjobs.com/Capital_One',
      active: true,
    },
  },
};
