version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    container_name: jobs-backend-prod
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: jobs-database-prod
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata-prod:/var/lib/postgresql/data

volumes:
  pgdata-prod:
